// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJyOhhOKSicEzhXV-KrBVnlPkd_bsjSxk',
    appId: '1:1055880010627:web:a5450630ddf4881cf174b6',
    messagingSenderId: '1055880010627',
    projectId: 'flutter-chat-app-4894a',
    authDomain: 'flutter-chat-app-4894a.firebaseapp.com',
    storageBucket: 'flutter-chat-app-4894a.appspot.com',
    measurementId: 'G-RXL3KH80D0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0Ee6bgKmPUl_C0ncvQm-xDq1797UObqM',
    appId: '1:1055880010627:android:5ba44d50bebd3297f174b6',
    messagingSenderId: '1055880010627',
    projectId: 'flutter-chat-app-4894a',
    storageBucket: 'flutter-chat-app-4894a.appspot.com',
  );
}
